/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/products": {
    /** Retrieve a list of products */
    get: operations["getProductsList"];
    parameters: {
      query: {
        sort: string;
      };
    };
  };
  "/products/{id}": {
    /** Retrieve a single product by ID */
    get: operations["getProduct"];
    parameters: {
      path: {
        id: string;
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Product: {
      /** @description The user's unique ID */
      id: number;
      /** @description The user's name */
      name: string;
      /** @description The user's description */
      description?: string;
    };
    Error: {
      /** @description The error message */
      message: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  getProductsList: {
    /** Retrieve a list of products */
    responses: {
      /** @description A list of products */
      200: {
        content: {
          "application/json": (components["schemas"]["Product"])[];
        };
      };
    };
  };
  getProduct: {
    /** Retrieve a single product by ID */
    responses: {
      /** @description The requested user */
      200: {
        content: {
          "application/json": components["schemas"]["Product"];
        };
      };
      /** @description User not found */
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
}
